// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://vf76rcabozh3zfeqxftt3jv7lu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rv4dr6g4sberli66wo6ulqbcbe",
    "aws_content_delivery_bucket": "myapp-20200225140323-hostingbucket-test",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://myapp-20200225140323-hostingbucket-test.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:12cc74fd-4372-428d-b5f4-0af8af7f2e5e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3g0NUUL2v",
    "aws_user_pools_web_client_id": "58go4f2l6c6oibvi8h7bv2ordb",
    "oauth": {},
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
